'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.5477
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On



Partial Public Class Contactenos

    '''<summary>
    '''cnt_contentDespuesdeGuardar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cnt_contentDespuesdeGuardar As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''cnt_contentAntesdeGuardar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cnt_contentAntesdeGuardar As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''Email control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Email As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''TextoComentario control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextoComentario As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''imgCaptchaReg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgCaptchaReg As Global.System.Web.UI.HtmlControls.HtmlImage

    '''<summary>
    '''txtImagenCaptchaReg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtImagenCaptchaReg As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''LblImagenCaptchaRerPersonal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblImagenCaptchaRerPersonal As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''btnEnviarComentario control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnEnviarComentario As Global.System.Web.UI.WebControls.Button
End Class
