'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión del motor en tiempo de ejecución:2.0.50727.5485
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On



Partial Public Class Destacados

    '''<summary>
    '''Control LblDestacadoTituloPrincipal.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents LblDestacadoTituloPrincipal As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''Control lblSigno1.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents lblSigno1 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''Control hrefTitulo1.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents hrefTitulo1 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''Control lblSigno2.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents lblSigno2 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''Control hrefTitulo2.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents hrefTitulo2 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''Control lblSigno3.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents lblSigno3 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''Control hrefTitulo3.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents hrefTitulo3 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''Control lblSigno4.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents lblSigno4 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''Control hrefTitulo4.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents hrefTitulo4 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''Control lblSigno5.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents lblSigno5 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''Control hrefTitulo5.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents hrefTitulo5 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''Control tblResultadoArticulos.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents tblResultadoArticulos As Global.System.Web.UI.WebControls.Table

    '''<summary>
    '''Control TagPaginacion.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents TagPaginacion As Global.System.Web.UI.HtmlControls.HtmlGenericControl
End Class
