'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.5477
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On



Partial Public Class NuevaContrasena

    '''<summary>
    '''NombreTipoEnvio control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NombreTipoEnvio As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''cnt_contentGuardar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cnt_contentGuardar As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''MensajedelEnvio control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MensajedelEnvio As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''cnt_contentMail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cnt_contentMail As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''Clave control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Clave As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btnRegistro control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnRegistro As Global.System.Web.UI.WebControls.Button
End Class
