'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.5477
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On



Partial Public Class PruebasCorreo

    '''<summary>
    '''form1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''txtcontrasena control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtcontrasena As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btnVer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnVer As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''lblError control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblError As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Tabla_Principal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Tabla_Principal As Global.System.Web.UI.HtmlControls.HtmlTable

    '''<summary>
    '''txtServidorN control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtServidorN As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtPuertoN control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPuertoN As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtCredenciaMailN control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCredenciaMailN As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtCrendetialPassN control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCrendetialPassN As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtDeN control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDeN As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtParaN control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtParaN As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtAsuntoN control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAsuntoN As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtContenidoN control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtContenidoN As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''BtnEnviar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnEnviar As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''txtServidorOut control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtServidorOut As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtPuertoOut control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPuertoOut As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtCredenciaMailOut control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCredenciaMailOut As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtCrendetialPassOut control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCrendetialPassOut As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtDeOut control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDeOut As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtParaOut control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtParaOut As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtAsuntoOut control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAsuntoOut As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtContenidoOut control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtContenidoOut As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''BtnEnviarOut control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnEnviarOut As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''lblErrorEnvioMail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblErrorEnvioMail As Global.System.Web.UI.WebControls.Label
End Class
