'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión del motor en tiempo de ejecución:2.0.50727.5485
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On



Partial Public Class UploadFile

    '''<summary>
    '''Control cnt_contentDespuesdeGuardar.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents cnt_contentDespuesdeGuardar As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''Control cnt_contentAntesdeGuardar.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents cnt_contentAntesdeGuardar As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''Control Titulo.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents Titulo As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''Control Resumen.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents Resumen As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Control TextoColaboracion.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents TextoColaboracion As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Control Publicacion.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents Publicacion As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Control File_U.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents File_U As Global.System.Web.UI.HtmlControls.HtmlInputFile

    '''<summary>
    '''Control imgCaptchaReg.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents imgCaptchaReg As Global.System.Web.UI.HtmlControls.HtmlImage

    '''<summary>
    '''Control txtImagenCaptchaReg.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents txtImagenCaptchaReg As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''Control LblImagenCaptchaRerPersonal.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents LblImagenCaptchaRerPersonal As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''Control btnEnviarColaboracion.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents btnEnviarColaboracion As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''Control hidEstaRegistrado.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents hidEstaRegistrado As Global.System.Web.UI.HtmlControls.HtmlInputHidden
End Class
