'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.5477
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On



Partial Public Class Ver_Mis_Publicaciones

    '''<summary>
    '''hrefTitulo1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hrefTitulo1 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''lblNombreNivel1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNombreNivel1 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''hrefTitulo2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hrefTitulo2 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''lblNombreNivel2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNombreNivel2 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''LblPublicacionTitulo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblPublicacionTitulo As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''tblResultadoPublicacion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tblResultadoPublicacion As Global.System.Web.UI.WebControls.Table

    '''<summary>
    '''TagPaginacion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TagPaginacion As Global.System.Web.UI.HtmlControls.HtmlGenericControl
End Class
