'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión del motor en tiempo de ejecución:2.0.50727.5485
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On



Partial Public Class VerArticulo

    '''<summary>
    '''Control TituloArticulo.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents TituloArticulo As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''Control lblSigno1.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents lblSigno1 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''Control ahref_Origen.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents ahref_Origen As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''Control lbl_NombreOrigen.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents lbl_NombreOrigen As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''Control lblSigno2.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents lblSigno2 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''Control ahref_SubSeccion.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents ahref_SubSeccion As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''Control lbl_NombreSubSeccion.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents lbl_NombreSubSeccion As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''Control lblNombre.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents lblNombre As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''Control ImgAutor.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents ImgAutor As Global.System.Web.UI.HtmlControls.HtmlImage

    '''<summary>
    '''Control NombreAutorHref.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents NombreAutorHref As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''Control LblFecha.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents LblFecha As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''Control divRating.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents divRating As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''Control pEtiquetas.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents pEtiquetas As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''Control imagenDescargaDoc.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents imagenDescargaDoc As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''Control imagenDescargaPdf.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents imagenDescargaPdf As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''Control imagenDescargaPpt.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents imagenDescargaPpt As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''Control imagenDescargaOtro.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents imagenDescargaOtro As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''Control hdnFile.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents hdnFile As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''Control ahRef_VistaPrevia.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents ahRef_VistaPrevia As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''Control img_VistaPrevia.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents img_VistaPrevia As Global.System.Web.UI.HtmlControls.HtmlImage

    '''<summary>
    '''Control LblResena.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents LblResena As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''Control DivArticulo.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents DivArticulo As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''Control Iframe_Articulo.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents Iframe_Articulo As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''Control DivContenido.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents DivContenido As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''Control Lst_delAutor.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents Lst_delAutor As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''Control hidAutor.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents hidAutor As Global.System.Web.UI.HtmlControls.HtmlInputHidden
End Class
